name: CMake on Ubuntu

on:
  push:
    branches: [ "0.6" ]
  pull_request:
    branches: [ "0.6" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]
        cpp_compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v4

    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake # Установка последней доступной версии через APT
        cmake --version
        if [[ $(cmake --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+") != "3.28.3" ]]; then
          echo "Installing CMake 3.28.3..."
          wget https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3-linux-x86_64.sh -O cmake-install.sh
          sudo sh cmake-install.sh --skip-license --prefix=/usr/local
          rm cmake-install.sh
        fi
        cmake --version

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest
